version: '3.9'

networks:
  visio_network:
    driver: bridge
  kuka_network:
    driver: macvlan
    driver_opts:
      parent: ${KUKA_NETWORK_INTERFACE}  # Use environment variable
    ipam:
      config:
        - subnet: ${KUKA_SUBNET}  # Use environment variable

services:
  backend:
    build:
      context: ./backend
    ports:
      - "${PUBLIC_STATIC_SERVER_PORT}:${PUBLIC_STATIC_SERVER_PORT}"  # Expose public static server port to the host
    command: >
      bash -c "
      uvicorn main_oop:app --host 0.0.0.0 --port ${BACKEND_MAIN_PORT} --reload &
      uvicorn public_static_server:app --host 0.0.0.0 --port ${PUBLIC_STATIC_SERVER_PORT} --reload &
      uvicorn local_static_server:app --host 0.0.0.0 --port ${LOCAL_STATIC_SERVER_PORT} --reload
      "
    volumes:
      - ./backend:/app
    working_dir: /app
    networks:
      - visio_network
    profiles:
      - backend
    environment:
      - BACKEND_MAIN_PORT=${BACKEND_MAIN_PORT}
      - PUBLIC_STATIC_SERVER_PORT=${PUBLIC_STATIC_SERVER_PORT}
      - LOCAL_STATIC_SERVER_PORT=${LOCAL_STATIC_SERVER_PORT}
      - TOBII_CONNECT_URL=${TOBII_CONNECT_URL}
      # Any other environment variables needed

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"  # Expose frontend port
    command: >
      bash -c "
      cd vite && yarn dev --host
      "
    volumes:
      - ./frontend:/app
    working_dir: /app
    networks:
      - visio_network
    profiles:
      - frontend
    environment:
      - VITE_BACKEND_URL=${BACKEND_URL}
      - VITE_PUBLIC_STATIC_SERVER_URL=${PUBLIC_STATIC_SERVER_URL}
      # Any other environment variables needed

  sigma7:
    build:
      context: ./sigma7
    command: >
      bash -c "
      cd /workspaces/sigma7/sdk-3.7.3/bin && ./autoinit &&
      cd /workspaces/sigma7/codes/teleimpedance/bin/Debug && ./teleimpedance
      "
    volumes:
      - ./sigma7:/workspace
    working_dir: /workspace
    cap_add:
      - NET_ADMIN  # Allow network management for running configure_network.sh
    networks:
      - kuka_network  # Connect to the physical network
      - visio_network  # Connect to the Docker internal network
    profiles:
      - sigma7
    environment:
      - SIGMA7_PORT=${SIGMA7_PORT}
      # Any other environment variables needed

  tobii_connect:
    build:
      context: ./tobii_connect
    ports:
      - "${TOBII_CONNECT_PORT}:${TOBII_CONNECT_PORT}"  # Expose port if needed
    command: >
      bash -c "
      uvicorn capture:app --host 0.0.0.0 --port ${TOBII_CONNECT_PORT} --reload
      "
    volumes:
      - ./tobii_connect:/app
    working_dir: /app
    networks:
      - visio_network
    profiles:
      - tobii
    environment:
      - TOBII_CONNECT_PORT=${TOBII_CONNECT_PORT}
      # Any other environment variables needed
