version: '3.9'

networks:
  visio_network:
    driver: bridge
  kuka_network:
    driver: macvlan
    driver_opts:
      parent: enp0s31f6  # Replace with your actual Ethernet interface on the host
    ipam:
      config:
        - subnet: 192.180.1.0/24

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"  # Only expose port 8001 to the host
    command: >
      bash -c "
      uvicorn main_oop:app --host 0.0.0.0 --port 8000 --reload &
      uvicorn static_server:app --host 0.0.0.0 --port 8001 --reload
      "
    volumes:
      - ./backend:/app
    working_dir: /app
    networks:
      - visio_network
    profiles:
      - backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"  # Expose port 5173 for ngrok or external access
    command: >
      bash -c "
      cd vite && yarn dev --host
      "
    volumes:
      - ./frontend:/app
    working_dir: /app
    networks:
      - visio_network
    profiles:
      - frontend

  sigma7:
    build:
      context: ./sigma7
    command: >
      bash -c "
      cd /workspaces/sigma7/sdk-3.7.3/bin && ./autoinit &&
      cd /workspaces/sigma7/codes/teleimpedance/bin/Debug && ./teleimpedance
      "
    volumes:
      - ./sigma7:/workspace
    working_dir: /workspace
    cap_add:
      - NET_ADMIN  # Allow network management for running configure_network.sh
    networks:
      - kuka_network  # Connect to the physical network
      - visio_network  # Connect to the Docker internal network
    profiles:
      - sigma7

  tobii_connect:
    build:
      context: ./tobii_connect
    # ports:
    #   - "8011:8011"  # Expose only if needed for ngrok or external access
    command: >
      bash -c "
      uvicorn capture:app --host 0.0.0.0 --port 8011 --reload
      "
    volumes:
      - ./tobii_connect:/app
    working_dir: /app
    networks:
      - visio_network
    profiles:
      - tobii
